### ISSUE TITLE
User Story: Profile Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#10]
As a user, I can update my profile details, so that I can make corrections or provide updated profile information.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in
**WHEN** user visits ‘My Profile’ page
**THEN** they can see a prefilled form with their registered username, first name, last name, and email; also displayed are buttons to cancel and update, and a link to change their password.

- **GIVEN** that the user is logged in
**WHEN** user visits ‘My Profile’ page
**THEN** they can see a prefilled form with the username as read-only, and the rest as editable.

- **GIVEN** that the user is logged in and visiting the ‘My Profile’ page
**WHEN** user updates any of their profile details
**THEN** these are validated before changes are made in the database, and a feedback message is displayed when invalid.

- **GIVEN** that the user is logged in and visiting the ‘My Profile’ page
**WHEN** user clicks ‘cancel’
**THEN** the un-submitted changes in the form are cleared and credentials saved in the database are re-displayed on the page.

### TASKS:
- [x] Create a Profile page template
- [x] Add a form that includes username, first name, last name, and email.
- [x] Make the username input field read-only.
- [x] Add ‘cancel’ and ‘update’ button
- [x] Create a ‘Change Password' link
- [x] Validate any change in the first name, and display feedback message as appropriate
- [x] Validate any change in the last name, and display feedback message as appropriate
- [x] Validate any change in Email, and display a feedback message as appropriate

**Comment by marked-gil** [comment]
User story is completed.
