### ISSUE TITLE
User Story: My Tasks TODAY (Home) Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#11]
As a user, I can view my tasks for today, so that I can work on each task, make updates, mark them as complete, delete them if necessary, and add more tasks for the day.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in
**WHEN** the user visits the ‘My Tasks Today’ page
**THEN** they can see a list of all the tasks for the current date.

- **GIVEN** that the user is logged in and visiting the ‘My Tasks Today’ page 
**WHEN** they click the ‘add task’, ‘view’, or ‘delete’ links 
**THEN** they will be redirected to the respective page/modal.

- **GIVEN** that the user is logged in and visiting the ‘My Tasks Today’ page
**WHEN** a task is marked as ‘complete’
**THEN** it will be highlighted as complete.

### TASKS:
- [x] Create 'My Tasks Today' template
- [x] List all tasks for the current date
- [x] Add delete and view buttons
- [x] Allow the setting of a task as ‘complete’ by the user

**Comment by marked-gil** [comment]
User story is completed.
