### ISSUE TITLE
User Story: Filtering of My Tasks Today

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#12]
As a user, I can filter my tasks for the current day, so that it is easy to organize and find tasks.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in and visiting the ‘My Tasks Today’ page
**WHEN** the user filters the returned list of tasks by the options provided 
**THEN** only the filtered tasks will be displayed.

- **GIVEN** that the user is logged in and visiting the ‘My Tasks Today’ page
**WHEN** the user changes the order of the tasks in the list by the options provided
**THEN** reorganized tasks will be returned as per the option chosen.

### TASKS:
- [x] Allow re-ordering of the list by ‘priority’, ‘due time’
- [x] Allow filtering of the list by 'progress', and 'category'
- [x] By default, only show ‘to-do’, ‘overdue’, and ‘shared’ tasks and order by due_time

**Comment by marked-gil** [comment]
User story is completed.
