### ISSUE TITLE
User Story: My Tasks on SPECIFIC DATE Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#15]
As a user, I can view my tasks for a specific date, so that I can work on each task, make updates, mark them as complete, delete them if necessary, and add more tasks.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in
**WHEN** the user visits the ‘My Tasks on Specific Date’ page
**THEN** they can see a list of all the tasks for the specified date.

- **GIVEN** that the user is logged in and visiting the ‘My Tasks on Specific Date’ page
**WHEN** they click the ‘add task’, ‘edit’, or ‘delete’
**THEN** they will be redirected to the respective page/modal.

- **GIVEN** that the user is logged in and visiting the ‘My Tasks on Specific Date’ page
**WHEN** a task is marked as ‘complete’
**THEN** it will be highlighted as complete.

### TASKS:
- [x] Create My Tasks Tomorrow template
- [x] List all tasks for tomorrow
- [x] Add 'delete', 'view', and 'done' button
- [x] Allow setting of the task as ‘complete’ by the user

**Comment by marked-gil** [comment]
User story is completed.
