### ISSUE TITLE
User Story: My SHARED Tasks Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#17]
As a user, I can view my shared tasks (tasks I shared and tasks shared with me), so that I can work on each task, make updates, mark them as complete, and delete them if necessary.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in
**WHEN** the user visits the ‘My Shared Tasks’ page
**THEN** they can see a list of all my shared tasks.

- **GIVEN** that the user is logged in and visiting the ‘My Shared Tasks’ page
**WHEN** they click the ‘edit’ or ‘delete’
**THEN** they will be redirected to the respective page/modal.

- **GIVEN** that the user is logged in and visiting the ‘My Shared Tasks’ page
**WHEN** a task is marked as ‘complete’ 
**THEN** it will be highlighted as complete.

### TASKS:
- [x] Create ‘My Shared Tasks’ template
- [x] List my shared tasks
- [x] Add 'delete', 'view', and 'done' button
- [x] Allow setting of the task as ‘complete’ by the user

**Comment by marked-gil** [comment]
User story is completed.
