### ISSUE TITLE
User Story: Filtering of My Shared Tasks

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#18]
As a user, I can filter my shared tasks, so that it is easy to organize and find tasks.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in and visiting the ‘My Shared Tasks’ page
**WHEN** the user filters the returned list of shared tasks by the options provided
**THEN** only the filtered tasks will be displayed.

- **GIVEN** that the user is logged in and visiting the ‘My Shared Tasks’ page
**WHEN** the user changes the order of the tasks in the list by the options provided
**THEN** reorganized tasks will be returned as per the option chosen.

### TASKS:
- [x] Allow re-ordering of the list by ‘priority’, ‘due time’
- [x] Allow filtering of the list by ‘progress’, and ‘category’
- [x] By default, only show ‘to-do’ and ‘overdue’ tasks and order by due_time

**Comment by marked-gil** [comment]
User story is completed.
