### ISSUE TITLE
User Story: Filtering of My Overdue Tasks

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#20]
As a user, I can filter my overdue tasks, so that it is easy to organize and find tasks.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in and visiting the ‘My Overdue Tasks’ page
**WHEN** the user filters the returned list of overdue tasks by the options provided
**THEN** only the filtered tasks will be displayed.

- **GIVEN** that the user is logged in and visiting the ‘My Overdue Tasks’ page
**WHEN** the user changes the order of the tasks in the list by the options provided
**THEN** reorganized tasks will be returned as per the option chosen.

### TASKS:
- [x] Allow re-ordering of the list by ‘priority’, ‘due date/time’
- [x] Allow filtering of the list
- [x] By default, show all overdue tasks belonging to any category and including 'shared' tasks; and order by due date/time in ascending order.

**Comment by marked-gil** [comment]
User story is completed,
