### ISSUE TITLE
User Story: My ALL TODO Tasks Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#21]
As a user, I can view the todo tasks, so that I can see all my upcoming tasks, and have a link to each tasks page that I want to view.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in
**WHEN** the user visits the ‘All Todo Tasks’ page
**THEN** they can see a list of all dates that contain tasks with their corresponding number of tasks.

### TASKS:
- [x] Create ‘My All Tasks’ template
- [x] Have a link that will redirect to the 'My Task on a Specific Date' page
- [x] Add ‘add task’ button on each date

**Comment by marked-gil** [comment]
User story is completed.
