### ISSUE TITLE
User Story: Filtering of Tasks in ‘My All TO-DO Tasks’ Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#22]
As a user, I can filter all my tasks, so that it is easy to organize and find tasks.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in and visiting the ‘My All TO-DO Tasks’ page 
**WHEN** the user filters the returned list of tasks
**THEN** only the filtered item/s will be displayed.

- **GIVEN** that the user is logged in and visiting the ‘My All TO-DO Tasks’ page 
**WHEN** the user changes the order of the tasks in the list by the options provided
**THEN** reorganized tasks will be returned as per the option chosen.

### TASKS:
- [x] Allow re-ordering of the list of to-do tasks and priority
- [x] Allow filtering of the list by category
- [x] By default, show all todo tasks in ascending order based on due dates

**Comment by marked-gil** [comment]
User story is completed.
