### ISSUE TITLE
User Story: My Tasks By Category Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#23]
As a user, I can view my tasks that belong to a specific category, so that I can work on each task, make updates, mark them as complete, and delete them if necessary.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in
**WHEN** the user visits the ‘My Tasks by Category’ page
**THEN** they can see a list of all their tasks that belong to the specific category.

- **GIVEN** that the user is logged in and visiting the ‘My Tasks by Category’ page
**WHEN** a task is marked as ‘complete’
**THEN** it will be highlighted as complete.

### TASKS:
- [x] Create ‘My Tasks by Category’ template
- [x] Display a list of the category’s tasks
- [x] Add 'delete', 'view', and 'done' button on each task
- [x] Allow setting of the task as ‘complete’ by the user

**Comment by marked-gil** [comment]
User story is completed.
