### ISSUE TITLE
User Story: Filtering of Tasks in a Category

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#24]
As a user, I can filter all the tasks in the ‘My Tasks by Category’ page, so that it is easy to organize and find tasks.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in and visiting the ‘My Tasks by Category’ page
**WHEN** the user filters the returned list tasks by the options provided 
**THEN** only the filtered tasks will be displayed.

- **GIVEN** that the user is logged in and visiting the ‘My Tasks by Category’ page
**WHEN** the user changes the order of the tasks in the list by the options provided
**THEN** reorganized tasks will be returned as per the option chosen.

### TASKS:
- [x] Allow re-ordering of the list by ‘priority’, ‘due date’
- [x] Allow filtering of the list by ‘progress’
- [x] By default, only show ‘to-do’, ‘overdue’, and 'shared' tasks and order by due date/time

**Comment by marked-gil** [comment]
User story is completed.
