### ISSUE TITLE
User Story: Task Details Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#25]
As a user, I can view the details of a task, so that I can see its description and other details.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in
**WHEN** the user visits the ‘Task Details’ page 
**THEN** the details of the task will be displayed.

### TASKS:
- [x] Create the Task Details template
- [x] Display the task’s category, due date and time, priority, and progress, task name, and description
- [x] Display the owner of the task
- [x] Add 'edit' button/link to the task name and description area
- [x] Allow toggle between 'edit' and 'save' button on each editable field.
- [x] Make the following editable: category, due date and time, and priority.

**Comment by marked-gil** [comment]
User story is completed.
