### ISSUE TITLE
User Story: Add Task

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#26]
As a user, I can add new tasks, so that the application works as intended.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in 
**WHEN** they click ‘add task’
**THEN** the modal for adding a new task appears.

- **GIVEN** that the Add Task modal is visible and category name and description are inputted
**WHEN** they click ‘add’
**THEN** the new category will be posted to the API and saved on the database.

- **GIVEN** that the Add Task modal is visible
**WHEN** the category name is empty and ‘add’ is clicked
**THEN** feedback message will appear and the form will not be posted to API.

### TASKS:
- [x] Create a modal (lightbox) that contains input fields for the task name and description
- [x] Add option boxes for categories, and priority
- [x] Add fields to set the due date and time
- [x] Add cancel and 'add' buttons
- [x] Allow setting of category, due date and time, and priority
- [x] Prevent submission of form when task name is empty
- [x] Submit the form when the ‘add’ button is clicked
- [x] Remove or hide modal when ‘cancel’ is clicked

**Comment by marked-gil** [comment]
Use story is completed
