### ISSUE TITLE
User Story: Delete Task

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#27]
As a user, I can delete tasks, so that I can freely organize my tasks and remove unwanted tasks.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the logged-in user is the owner of the task
**WHEN** ‘delete’ for the task is clicked
**THEN** the request will be posted to the API and removed from the database.

### TASKS:
- [x] Add a ‘delete’ button in the ‘Task Details’ page when the current user is the owner
- [x] Add a ‘delete’ button for each task in a list when the current user is the owner
- [x] Allow removal of task from the database when ‘delete’ is clicked
- [x] Remove the deleted task from the displayed list when 'delete' is clicked

**Comment by marked-gil** [comment]
User story is completed.
