### ISSUE TITLE
User Story: Edit Task

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#28]
As a user, I can update the task I created, so that mistakes can be amended or information can be improved.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is on the page where tasks are listed
**WHEN** ‘view’ is clicked  
**THEN** the user is redirected to the task’s specific page.

- **GIVEN** that the user is the owner of the task and is on the task’s details/specific page
**WHEN** ‘edit’ is clicked on a particular field
**THEN** the field becomes editable.

### TASKS:
- [x] Add an ‘edit’ button or link to each task owned by the current user
- [x] Add 'view' button to each task that redirects the user to the Task Details page when clicked
- [x] Allow the owner of the task to update the corresponding field when ‘edit’ is clicked.

**Comment by marked-gil** [comment]
Use story is completed.
