### ISSUE TITLE
User Story: Task Sharing

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#29]
As a user, I can add or remove users from a task, so that I can control task participants.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the logged-in user is on a page with the ‘shared with’ link is present on a task
**WHEN** the user clicks the ‘shared with’ link
**THEN** the ‘Task Sharing’ modal pops out.

- **GIVEN** that the ‘Task Sharing’ modal is visible
**WHEN** the user clicks ‘remove all participants’
**THEN** all the usernames sharing the task are removed.

- **GIVEN** that the ‘Task Sharing’ modal is visible
**WHEN** the user clicks on a username the task is being shared to
**THEN** an option to remove it will appear.

- **GIVEN** that the ‘Task Sharing’ modal is visible
**WHEN** the user enters a username on the search bar and clicks ‘find’
**THEN** the user that matches the search will be returned and can be added as a participant to the task via the ‘add’ button.

### TASKS:
- [x] Create a modal for managing task sharing
- [x] Add Task name and list of participants to the task
- [x] Add a search bar for the username of users to be added as new participants to the task
- [x] Allow removal of user/participant
- [x] Add the found user to the list of task participants by clicking on the ‘add’ link/button

**Comment by marked-gil** [comment]
User story is completed.
