### ISSUE TITLE
User Story: Search Results Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#30]
As a user, I can search for tasks using the search bar, so that I have the convenience in finding tasks with their title.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in
**WHEN** the user entered a task name in the search bar
**THEN** task names that match the query will be displayed.

### TASKS:
- [x] Create a search bar for finding tasks with the task names
- [x] List the tasks found by showing their task name, a snippet of their description, due date and time, and priority level.
- [x] Make the task name a link that redirects to the task’s details page
- [x] By default, arrange the results by due dates in ascending order

**Comment by marked-gil** [comment]
User story is completed.
