### ISSUE TITLE
User Story: Add Category

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#31]
As a user, I can add new categories, so that the tasks can be organized or grouped effectively by the user as they see fit.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in
**WHEN** they click ‘add' category'
**THEN** the modal for adding a new category appears.

### TASKS:
- [x] Create a modal (lightbox) that contains input fields for category name and description
- [x] Add cancel and save buttons
- [x] Prevent submission of form when category name is empty
- [x] Submit the form when the ‘save’ button is clicked
- [x] Remove or hide modal when ‘cancel’ is clicked

**Comment by marked-gil** [comment]
User story is completed.
