### ISSUE TITLE
User Story: Delete Category

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#33]
As a user, I can delete a category, so that I can freely organize my tasks and remove unwanted category and their associated tasks.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the logged-in user is the owner of the category and is visiting the ‘My Tasks by Category’ page
**WHEN** ‘delete’ button is clicked 
**THEN** the request will be posted to the API and the category will be removed from the database.

### TASKS:
- [x] Add a ‘delete’ button in the ‘My Tasks by Category’ page when the current user is the owner
- [x] Allow removal of the category and its associated tasks from the database when ‘delete’ is clicked
- [x] Redirect the user to the ‘My Tasks Today’ page after deleting the category.

**Comment by marked-gil** [comment]
User story is completed.
