### ISSUE TITLE
User Story: Add Task Comments

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#34]
As a user, I can write comments on a task or reply to another comment, so that I am able to add more details to the task if necessary or communicate with other users the task is shared with.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in and is visiting the Task Details page
**WHEN** the user clicks on the ‘add comment’ link
**THEN** a modal (lightbox) for the comment text area pops out.

- **GIVEN** that the comment text area is displayed
**WHEN** they click ‘submit’ without any character typed 
**THEN** a feedback message will show and the form will not be posted to the API.

- **GIVEN** that the comment was already posted successfully to the API
**WHEN**  the user views the page
**THEN** the submitted comment is displayed on the page.

### TASKS:
- [x] Create a comment section inside Task Details page
- [x] Add an ‘add comment’ link that, when clicked, will reveal the text area for the comment
- [x] Add the comment to the database when the ‘submit’ button is clicked.
- [x] Prevent submission of empty comments.
- [x] Display the added comments in the comment section.

**Comment by marked-gil** [comment]
User story is completed.
