### ISSUE TITLE
User Story: Allow Edit and Deletion of Comments

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#36]
As a user, I can edit and delete comments, so that mistakes can be rectified or improvements can be made.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the current user owns the comment
**WHEN** ‘edit’ is clicked 
**THEN** the message becomes editable.

- **GIVEN** that the current user owns the comment
**WHEN** ‘delete’ is clicked
**THEN** the message is deleted.

### TASKS:
- [x] Add ‘edit’ to each comment that belongs to the current user.
- [x] Add ‘delete’ to each comment that belongs to the current user.
- [x] Allow editing of comments when ‘edit’ is clicked by the current user.
- [x] Allow removal of comment when ‘delete’ is clicked by the current user.

**Comment by marked-gil** [comment]
User story is completed.
