### ISSUE TITLE
User Story: Sign Up

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#37]
As a user, I can register on the site, so that I can access and utilize its capability.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is on the registration page of the site
**WHEN** the user provides a valid username and password
**THEN** they are automatically signed in and redirected to the ‘Home’ page (or ‘All My Tasks’ page).

- **GIVEN** that the user is on the registration page of the site
**WHEN** the user provides an invalid username and password
**THEN** feedback message is displayed to inform the user of invalid credentials.

### TASKS:
- [x] Create a Sign-Up page that requests for username, and password (2x).
- [x] Add a ‘Register’ button that will submit the username and password provided by the new user.
- [x] Add a SIGN-IN link that will redirect to the Sign-In page
- [x] Username should be validated
- [x] Password should be validated
- [x] Add logo and app name

**Comment by marked-gil** [comment]
User story is completed.
