### ISSUE TITLE
User Story: Sign In

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#38]
As a user, I can log in to the site, so that I can access it and utilize its capability.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is registered and is visiting the ‘Sign In’ page
**WHEN** the user provides a valid username and password
**THEN** they can access and utilize the capability of the site.

- **GIVEN** that the user is registered and is visiting the ‘Sign In’ page
**WHEN** the user provides an invalid username and password
**THEN** feedback message is displayed to inform the user of invalid credentials.

### TASKS:
- [x] Create Sign-In page with a form that requests for username and password
- [x] Add a Login button to submit the inputted username and password
- [x] Add the ‘Forgot Password’ link which redirects to the ‘Reset Password’ page
- [x] Add a ‘Sign Up’ link which redirects to the ‘Sign Up Page’
- [x] Username should be validated
- [x] Password should be validated
- [x] Add logo and app name

**Comment by marked-gil** [comment]
User story is completed.
