### ISSUE TITLE
User Story: Nav Bar

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#40]
As a user, I can see a navigation bar, so that I can easily and efficiently navigate through the website.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the React app is created
**WHEN** when users visit and log in to the site
**THEN** they can see a nav bar at the top of the page.

### TASKS:
- [x] Create a nav bar with the following elements: logo and app name, search bar and button, nav menu, and user avatar.
- [x] Create a nav menu with the following elements: My Tasks, My Profile and Sign Out.
- [x] Make the nav bar only available when the user is signed in. The Sign-In and Registration page will have no nav bar.
- [x] Make the nav bar available on all pages except on the ‘Sign-In’ and Registration pages.

**Comment by marked-gil** [comment]
User story is completed.
