### ISSUE TITLE
User Story: Side Bar

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#41]
As a user, I can have easy access to the most useful menu items, so that the site can easily be navigated.

### ACCEPTANCE CRITERIA:
- The side bar is available at all times for large screen devices and contains the following links/buttons: ‘Add Task‘, ‘Today’, ‘Tomorrow’, ‘All My Tasks’, ‘Shared Tasks’, ‘Overdue Tasks’, the categories, and ‘add new category icon’. 

### TASKS:
- [x] Create a sidebar with the following links/buttons: ‘Add Task‘, ‘Today’, ‘Tomorrow’, ‘All My Tasks’, ‘Shared Tasks’, ‘Overdue Tasks’, the categories, and ‘add new category icon’, and ‘recently completed tasks’. 
- [x] In large screen devices, keep the sidebar always present.
- [x] In small screen devices, such as mobile devices, including the contents of the sidebar as part of the off-canvas that appears when the burger menu is tapped.

**Comment by marked-gil** [comment]
User story is completed.
