### ISSUE TITLE
User Story: Sign Out

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#42]
As a user, I can sign out from the site, so that I can keep my account secured after using the application.

### ACCEPTANCE CRITERIA:
- **GIVEN**  that the user is logged in
**WHEN** they click on ‘Sign Out'
**THEN** they will be redirected to the ‘Sign In’ page and access to the full functionality of the site is prevented.

### TASKS:
- [x] Create a ‘Sign Out’ button on the Nav bar and make it visible when the user is logged-in
- [x] Redirect the user to the ‘Sign In’ page when they click on ‘Sign On’.
- [x] Prevent access to the rest of the pages when the user is signed out.

**Comment by marked-gil** [comment]
User story is completed.
