### ISSUE TITLE
User Story: Delete Account/Profile

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#43]
As a user, I can delete my account or profile, so that I will have full control of reclaiming my privacy when I feel the need.

### ACCEPTANCE CRITERIA:
- **GIVEN** that the user is logged in and is on the ‘My Profile’ page 
**WHEN** the user clicks on ‘Delete Account’
**THEN** a modal pops up requesting for the client to enter their password.

- **GIVEN** that the modal for deleting an account is displayed
**WHEN** they enter their password and click ‘delete account’ 
**THEN** the user’s profile along with all data it created will be deleted from the database, and the user is redirected to the ‘Sign In’ page.

### TASKS:
- [x] Create a ‘Delete Account’ link/button on the ‘My Profile’ page
- [ ] Create a modal that contains a password field and a ‘delete account’ button
- [ ] Display the password modal when the user clicks on ‘Delete Account’ on the ‘My Profile’ page
- [ ] Validate the entered password on the modal after the user clicks ‘delete account’, and delete the account when the password is valid.
- [ ] Redirect the user to the ‘Sign In’ page when the profile is successfully deleted, and show a feedback message.
