### ISSUE TITLE
User Story: Front-end Framework Use

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/tasks-master-react#9]
As a developer, I can use React-Bootstrap as a front-end framework, so that building this project will be quicker.

### ACCEPTANCE CRITERIA:
- React-Bootstrap is used to help build the site’s front-end structure more quicker.

### TASKS:
- [x] Install React-Bootstrap is installed and ready to use.
- [x] Add the React-Bootstrap CSS link on the <head> of index.html
- [x] In the index.html, add `crossorigin` attribute with `use-credentials` value in the manifest import - to remove the console error

**Comment by marked-gil** [comment]
User story is completed.
